### ISSUE TITLE
Module version: 1.1 not work on vc version 3.96.0

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-customer-export-import#66]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Microsoft Edge Versão 97.0.1072.62 (Compilação oficial) (64 bits)
- Platform version: 3.96.0
- Module version: 1.1

### Expected behavior
Module work on v.c version 3.96

### Actual behavior
modulo no start

### Steps to reproduce
1. update vc modulo to version 3.96
2. Install modulo customer-export-import
3. erro on load modulo

![image](https://user-images.githubusercontent.com/20837564/149667534-a925a06f-9983-4b6c-b08d-b4a2f5eb9510.png)

VirtoCommerce.CustomerExportImport 1.1.0
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Could not load type 'VirtoCommerce.Platform.Core.Assets.BlobInfo' from assembly 'VirtoCommerce.Platform.Core, Version=3.96.0.0, Culture=neutral, PublicKeyToken=null'. at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.RuntimeModule.GetTypes() at System.Reflection.Assembly.GetTypes() at VirtoCommerce.Platform.Modules.ModuleInitializer.CreateModule(ModuleInfo moduleInfo) in /home/runner/work/vc-platform/vc-platform/src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs:line 144 at VirtoCommerce.Platform.Modules.ModuleInitializer.Initialize(ModuleInfo moduleInfo) in /home/runner/work/vc-platform/vc-platform/src/VirtoCommerce.Platform.Modules/ModuleInitializer.cs:line 55 System.TypeLoadException: Could not load type 'VirtoCommerce.Platform.Core.Assets.BlobInfo' from assembly 'VirtoCommerce.Platform.Core, Version=3.96.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7894 has been created

**Comment by dvvkgd** [comment]
Hi, @JoseCaetanoNeto. This module is optional and not yet ready to use. At this point, you need to remove the module.

**Comment by JoseCaetanoNeto** [comment]
I need to import approximately 1000 clients which are in a csv file. Any suggestions on how to do this without this module?

**Comment by dvvkgd** [comment]
@JoseCaetanoNeto  We are just now implementing the import of contacts. We didn't have this module before. Because of this, we don't have a workaround. The only thing I could advise is to try using the API to create contacts.
Also I advise you to remove the CustomerExportImport 1.1.0 module, as it is not ready yet.

**Comment by Vectorfield4** [comment]
Hi @JoseCaetanoNeto! This module is not production-ready right now. All fixes are planned on Q2-2022, so you cannot use the latest platform with v1.1.0.

Btw, you need to install 3 modules after you updated to the platform 3.94+ ([Release note](https://github.com/VirtoCommerce/vc-platform/releases/tag/3.94.0))
1. https://github.com/VirtoCommerce/vc-module-assets
2. https://github.com/VirtoCommerce/vc-module-filesystem-assets
3. https://github.com/VirtoCommerce/vc-module-azureblob-assets
